
print("Hello World")
print("Hello Tasfia Tanjim Sadia")
print("Hello Ariyan Arafin Mehedi")
print ("Hello Adiyan Adnan Mahofi")

print ("calculator made by sadia")

num1 = int(input("first number"))
sign = input ("enter a sign")
num2 = int (input("second number"))
if sign == "+":
    print (num1 + num2)
elif sign == "-":
    print (num1 - num2)
elif sign == "*":
    print (num1 * num2) 
elif sign == "/":
    print (num1 / num2)
else :
    print ("something went wrong")

